import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.sqldelight)
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.sqldelight.runtime)
            implementation(libs.ktor.client.core)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.ktor.client.mock)
        }
        androidMain.dependencies {
            implementation(libs.androidx.activity.compose)
            implementation(libs.sqldelight.android.driver)
            implementation(libs.ktor.client.okhttp)
            implementation(libs.google.play.services.auth)
        }
        androidUnitTest.dependencies {
            implementation(libs.sqldelight.sqlite.driver)
        }
        iosMain.dependencies {
            implementation(libs.sqldelight.native.driver)
            implementation(libs.ktor.client.darwin)
        }
    }
}

android {
    namespace = "com.habitsheet.app"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.habitsheet.app"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = providers.gradleProperty("appVersionCode").get().toInt()
        versionName = providers.gradleProperty("appVersionName").get()
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    packaging {
        resources.excludes += "/META-INF/{AL2.0,LGPL2.1}"
    }
}

sqldelight {
    databases {
        create("HabitsDatabase") {
            packageName.set("com.habitsheet.database")
        }
    }
}

compose.resources {
    packageOfResClass = "com.habitsheet.resources"
}

val appVersionName = providers.gradleProperty("appVersionName")
val appVersionCode = providers.gradleProperty("appVersionCode")
val iosVersionFile = rootProject.layout.projectDirectory.file("iosApp/Config/Version.xcconfig")

// Generates iosApp/Config/Version.xcconfig from gradle.properties (committed, so Xcode works without Gradle).
val syncIosVersion by tasks.registering {
    group = "release"
    description = "Writes iosApp/Config/Version.xcconfig from appVersionName/appVersionCode."
    inputs.property("name", appVersionName)
    inputs.property("code", appVersionCode)
    outputs.file(iosVersionFile)
    doLast {
        val f = iosVersionFile.asFile
        f.parentFile.mkdirs()
        f.writeText(
            listOf(
                "// GENERATED by `./gradlew :composeApp:syncIosVersion` from gradle.properties. Do not edit.",
                "MARKETING_VERSION = ${appVersionName.get()}",
                "CURRENT_PROJECT_VERSION = ${appVersionCode.get()}",
            ).joinToString(separator = "\n", postfix = "\n"),
        )
    }
}
